[tool.poetry]
name = "geo_py_utils"
version = "0.3.1"
description = "Python functions for generic geospatial manipulations"
authors = ["Charles Gauvin"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
