[tool.poetry]
name = "geo_py_utils"
version = "0.1.0"
description = "Python functions for generic geospatial manipulations"
authors = ["Charles Gauvin"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
